// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/src/log_structure.proto

package ProtoDefs;

public final class LogStructure {
  private LogStructure() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LineOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoDefs.Line)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint64 logical_order = 1;</code>
     * @return The logicalOrder.
     */
    long getLogicalOrder();

    /**
     * <code>bool is_user_method = 2;</code>
     * @return The isUserMethod.
     */
    boolean getIsUserMethod();

    /**
     * <code>bool is_call2 = 3;</code>
     * @return The isCall2.
     */
    boolean getIsCall2();

    /**
     * <code>string method_name = 4;</code>
     * @return The methodName.
     */
    java.lang.String getMethodName();
    /**
     * <code>string method_name = 4;</code>
     * @return The bytes for methodName.
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>repeated .ProtoDefs.Param parameters = 5;</code>
     */
    java.util.List<ProtoDefs.LogStructure.Param> 
        getParametersList();
    /**
     * <code>repeated .ProtoDefs.Param parameters = 5;</code>
     */
    ProtoDefs.LogStructure.Param getParameters(int index);
    /**
     * <code>repeated .ProtoDefs.Param parameters = 5;</code>
     */
    int getParametersCount();

    /**
     * <code>uint64 BBloc = 6;</code>
     * @return The bBloc.
     */
    long getBBloc();
  }
  /**
   * Protobuf type {@code ProtoDefs.Line}
   */
  public  static final class Line extends
      com.google.protobuf.GeneratedMessageLite<
          Line, Line.Builder> implements
      // @@protoc_insertion_point(message_implements:ProtoDefs.Line)
      LineOrBuilder {
    private Line() {
      methodName_ = "";
      parameters_ = emptyProtobufList();
    }
    public static final int LOGICAL_ORDER_FIELD_NUMBER = 1;
    private long logicalOrder_;
    /**
     * <code>uint64 logical_order = 1;</code>
     * @return The logicalOrder.
     */
    @java.lang.Override
    public long getLogicalOrder() {
      return logicalOrder_;
    }
    /**
     * <code>uint64 logical_order = 1;</code>
     * @param value The logicalOrder to set.
     */
    private void setLogicalOrder(long value) {
      
      logicalOrder_ = value;
    }
    /**
     * <code>uint64 logical_order = 1;</code>
     */
    private void clearLogicalOrder() {
      
      logicalOrder_ = 0L;
    }

    public static final int IS_USER_METHOD_FIELD_NUMBER = 2;
    private boolean isUserMethod_;
    /**
     * <code>bool is_user_method = 2;</code>
     * @return The isUserMethod.
     */
    @java.lang.Override
    public boolean getIsUserMethod() {
      return isUserMethod_;
    }
    /**
     * <code>bool is_user_method = 2;</code>
     * @param value The isUserMethod to set.
     */
    private void setIsUserMethod(boolean value) {
      
      isUserMethod_ = value;
    }
    /**
     * <code>bool is_user_method = 2;</code>
     */
    private void clearIsUserMethod() {
      
      isUserMethod_ = false;
    }

    public static final int IS_CALL2_FIELD_NUMBER = 3;
    private boolean isCall2_;
    /**
     * <code>bool is_call2 = 3;</code>
     * @return The isCall2.
     */
    @java.lang.Override
    public boolean getIsCall2() {
      return isCall2_;
    }
    /**
     * <code>bool is_call2 = 3;</code>
     * @param value The isCall2 to set.
     */
    private void setIsCall2(boolean value) {
      
      isCall2_ = value;
    }
    /**
     * <code>bool is_call2 = 3;</code>
     */
    private void clearIsCall2() {
      
      isCall2_ = false;
    }

    public static final int METHOD_NAME_FIELD_NUMBER = 4;
    private java.lang.String methodName_;
    /**
     * <code>string method_name = 4;</code>
     * @return The methodName.
     */
    @java.lang.Override
    public java.lang.String getMethodName() {
      return methodName_;
    }
    /**
     * <code>string method_name = 4;</code>
     * @return The bytes for methodName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(methodName_);
    }
    /**
     * <code>string method_name = 4;</code>
     * @param value The methodName to set.
     */
    private void setMethodName(
        java.lang.String value) {
      value.getClass();
  
      methodName_ = value;
    }
    /**
     * <code>string method_name = 4;</code>
     */
    private void clearMethodName() {
      
      methodName_ = getDefaultInstance().getMethodName();
    }
    /**
     * <code>string method_name = 4;</code>
     * @param value The bytes for methodName to set.
     */
    private void setMethodNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      methodName_ = value.toStringUtf8();
      
    }

    public static final int PARAMETERS_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.ProtobufList<ProtoDefs.LogStructure.Param> parameters_;
    /**
     * <code>repeated .ProtoDefs.Param parameters = 5;</code>
     */
    @java.lang.Override
    public java.util.List<ProtoDefs.LogStructure.Param> getParametersList() {
      return parameters_;
    }
    /**
     * <code>repeated .ProtoDefs.Param parameters = 5;</code>
     */
    public java.util.List<? extends ProtoDefs.LogStructure.ParamOrBuilder> 
        getParametersOrBuilderList() {
      return parameters_;
    }
    /**
     * <code>repeated .ProtoDefs.Param parameters = 5;</code>
     */
    @java.lang.Override
    public int getParametersCount() {
      return parameters_.size();
    }
    /**
     * <code>repeated .ProtoDefs.Param parameters = 5;</code>
     */
    @java.lang.Override
    public ProtoDefs.LogStructure.Param getParameters(int index) {
      return parameters_.get(index);
    }
    /**
     * <code>repeated .ProtoDefs.Param parameters = 5;</code>
     */
    public ProtoDefs.LogStructure.ParamOrBuilder getParametersOrBuilder(
        int index) {
      return parameters_.get(index);
    }
    private void ensureParametersIsMutable() {
      com.google.protobuf.Internal.ProtobufList<ProtoDefs.LogStructure.Param> tmp = parameters_;
      if (!tmp.isModifiable()) {
        parameters_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .ProtoDefs.Param parameters = 5;</code>
     */
    private void setParameters(
        int index, ProtoDefs.LogStructure.Param value) {
      value.getClass();
  ensureParametersIsMutable();
      parameters_.set(index, value);
    }
    /**
     * <code>repeated .ProtoDefs.Param parameters = 5;</code>
     */
    private void addParameters(ProtoDefs.LogStructure.Param value) {
      value.getClass();
  ensureParametersIsMutable();
      parameters_.add(value);
    }
    /**
     * <code>repeated .ProtoDefs.Param parameters = 5;</code>
     */
    private void addParameters(
        int index, ProtoDefs.LogStructure.Param value) {
      value.getClass();
  ensureParametersIsMutable();
      parameters_.add(index, value);
    }
    /**
     * <code>repeated .ProtoDefs.Param parameters = 5;</code>
     */
    private void addAllParameters(
        java.lang.Iterable<? extends ProtoDefs.LogStructure.Param> values) {
      ensureParametersIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, parameters_);
    }
    /**
     * <code>repeated .ProtoDefs.Param parameters = 5;</code>
     */
    private void clearParameters() {
      parameters_ = emptyProtobufList();
    }
    /**
     * <code>repeated .ProtoDefs.Param parameters = 5;</code>
     */
    private void removeParameters(int index) {
      ensureParametersIsMutable();
      parameters_.remove(index);
    }

    public static final int BBLOC_FIELD_NUMBER = 6;
    private long bBloc_;
    /**
     * <code>uint64 BBloc = 6;</code>
     * @return The bBloc.
     */
    @java.lang.Override
    public long getBBloc() {
      return bBloc_;
    }
    /**
     * <code>uint64 BBloc = 6;</code>
     * @param value The bBloc to set.
     */
    private void setBBloc(long value) {
      
      bBloc_ = value;
    }
    /**
     * <code>uint64 BBloc = 6;</code>
     */
    private void clearBBloc() {
      
      bBloc_ = 0L;
    }

    public static ProtoDefs.LogStructure.Line parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProtoDefs.LogStructure.Line parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProtoDefs.LogStructure.Line parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProtoDefs.LogStructure.Line parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProtoDefs.LogStructure.Line parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProtoDefs.LogStructure.Line parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProtoDefs.LogStructure.Line parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProtoDefs.LogStructure.Line parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProtoDefs.LogStructure.Line parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ProtoDefs.LogStructure.Line parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProtoDefs.LogStructure.Line parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProtoDefs.LogStructure.Line parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ProtoDefs.LogStructure.Line prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code ProtoDefs.Line}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ProtoDefs.LogStructure.Line, Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoDefs.Line)
        ProtoDefs.LogStructure.LineOrBuilder {
      // Construct using ProtoDefs.LogStructure.Line.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint64 logical_order = 1;</code>
       * @return The logicalOrder.
       */
      @java.lang.Override
      public long getLogicalOrder() {
        return instance.getLogicalOrder();
      }
      /**
       * <code>uint64 logical_order = 1;</code>
       * @param value The logicalOrder to set.
       * @return This builder for chaining.
       */
      public Builder setLogicalOrder(long value) {
        copyOnWrite();
        instance.setLogicalOrder(value);
        return this;
      }
      /**
       * <code>uint64 logical_order = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogicalOrder() {
        copyOnWrite();
        instance.clearLogicalOrder();
        return this;
      }

      /**
       * <code>bool is_user_method = 2;</code>
       * @return The isUserMethod.
       */
      @java.lang.Override
      public boolean getIsUserMethod() {
        return instance.getIsUserMethod();
      }
      /**
       * <code>bool is_user_method = 2;</code>
       * @param value The isUserMethod to set.
       * @return This builder for chaining.
       */
      public Builder setIsUserMethod(boolean value) {
        copyOnWrite();
        instance.setIsUserMethod(value);
        return this;
      }
      /**
       * <code>bool is_user_method = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsUserMethod() {
        copyOnWrite();
        instance.clearIsUserMethod();
        return this;
      }

      /**
       * <code>bool is_call2 = 3;</code>
       * @return The isCall2.
       */
      @java.lang.Override
      public boolean getIsCall2() {
        return instance.getIsCall2();
      }
      /**
       * <code>bool is_call2 = 3;</code>
       * @param value The isCall2 to set.
       * @return This builder for chaining.
       */
      public Builder setIsCall2(boolean value) {
        copyOnWrite();
        instance.setIsCall2(value);
        return this;
      }
      /**
       * <code>bool is_call2 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsCall2() {
        copyOnWrite();
        instance.clearIsCall2();
        return this;
      }

      /**
       * <code>string method_name = 4;</code>
       * @return The methodName.
       */
      @java.lang.Override
      public java.lang.String getMethodName() {
        return instance.getMethodName();
      }
      /**
       * <code>string method_name = 4;</code>
       * @return The bytes for methodName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        return instance.getMethodNameBytes();
      }
      /**
       * <code>string method_name = 4;</code>
       * @param value The methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodName(
          java.lang.String value) {
        copyOnWrite();
        instance.setMethodName(value);
        return this;
      }
      /**
       * <code>string method_name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodName() {
        copyOnWrite();
        instance.clearMethodName();
        return this;
      }
      /**
       * <code>string method_name = 4;</code>
       * @param value The bytes for methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMethodNameBytes(value);
        return this;
      }

      /**
       * <code>repeated .ProtoDefs.Param parameters = 5;</code>
       */
      @java.lang.Override
      public java.util.List<ProtoDefs.LogStructure.Param> getParametersList() {
        return java.util.Collections.unmodifiableList(
            instance.getParametersList());
      }
      /**
       * <code>repeated .ProtoDefs.Param parameters = 5;</code>
       */
      @java.lang.Override
      public int getParametersCount() {
        return instance.getParametersCount();
      }/**
       * <code>repeated .ProtoDefs.Param parameters = 5;</code>
       */
      @java.lang.Override
      public ProtoDefs.LogStructure.Param getParameters(int index) {
        return instance.getParameters(index);
      }
      /**
       * <code>repeated .ProtoDefs.Param parameters = 5;</code>
       */
      public Builder setParameters(
          int index, ProtoDefs.LogStructure.Param value) {
        copyOnWrite();
        instance.setParameters(index, value);
        return this;
      }
      /**
       * <code>repeated .ProtoDefs.Param parameters = 5;</code>
       */
      public Builder setParameters(
          int index, ProtoDefs.LogStructure.Param.Builder builderForValue) {
        copyOnWrite();
        instance.setParameters(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .ProtoDefs.Param parameters = 5;</code>
       */
      public Builder addParameters(ProtoDefs.LogStructure.Param value) {
        copyOnWrite();
        instance.addParameters(value);
        return this;
      }
      /**
       * <code>repeated .ProtoDefs.Param parameters = 5;</code>
       */
      public Builder addParameters(
          int index, ProtoDefs.LogStructure.Param value) {
        copyOnWrite();
        instance.addParameters(index, value);
        return this;
      }
      /**
       * <code>repeated .ProtoDefs.Param parameters = 5;</code>
       */
      public Builder addParameters(
          ProtoDefs.LogStructure.Param.Builder builderForValue) {
        copyOnWrite();
        instance.addParameters(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .ProtoDefs.Param parameters = 5;</code>
       */
      public Builder addParameters(
          int index, ProtoDefs.LogStructure.Param.Builder builderForValue) {
        copyOnWrite();
        instance.addParameters(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .ProtoDefs.Param parameters = 5;</code>
       */
      public Builder addAllParameters(
          java.lang.Iterable<? extends ProtoDefs.LogStructure.Param> values) {
        copyOnWrite();
        instance.addAllParameters(values);
        return this;
      }
      /**
       * <code>repeated .ProtoDefs.Param parameters = 5;</code>
       */
      public Builder clearParameters() {
        copyOnWrite();
        instance.clearParameters();
        return this;
      }
      /**
       * <code>repeated .ProtoDefs.Param parameters = 5;</code>
       */
      public Builder removeParameters(int index) {
        copyOnWrite();
        instance.removeParameters(index);
        return this;
      }

      /**
       * <code>uint64 BBloc = 6;</code>
       * @return The bBloc.
       */
      @java.lang.Override
      public long getBBloc() {
        return instance.getBBloc();
      }
      /**
       * <code>uint64 BBloc = 6;</code>
       * @param value The bBloc to set.
       * @return This builder for chaining.
       */
      public Builder setBBloc(long value) {
        copyOnWrite();
        instance.setBBloc(value);
        return this;
      }
      /**
       * <code>uint64 BBloc = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBBloc() {
        copyOnWrite();
        instance.clearBBloc();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoDefs.Line)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ProtoDefs.LogStructure.Line();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "logicalOrder_",
              "isUserMethod_",
              "isCall2_",
              "methodName_",
              "parameters_",
              ProtoDefs.LogStructure.Param.class,
              "bBloc_",
            };
            java.lang.String info =
                "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0001\u0000\u0001\u0003\u0002\u0007" +
                "\u0003\u0007\u0004\u0208\u0005\u001b\u0006\u0003";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ProtoDefs.LogStructure.Line> parser = PARSER;
          if (parser == null) {
            synchronized (ProtoDefs.LogStructure.Line.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ProtoDefs.LogStructure.Line>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ProtoDefs.Line)
    private static final ProtoDefs.LogStructure.Line DEFAULT_INSTANCE;
    static {
      Line defaultInstance = new Line();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Line.class, defaultInstance);
    }

    public static ProtoDefs.LogStructure.Line getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Line> PARSER;

    public static com.google.protobuf.Parser<Line> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoDefs.Param)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string object = 1;</code>
     * @return The object.
     */
    java.lang.String getObject();
    /**
     * <code>string object = 1;</code>
     * @return The bytes for object.
     */
    com.google.protobuf.ByteString
        getObjectBytes();

    /**
     * <code>string type = 2;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>repeated string value = 3;</code>
     * @return A list containing the value.
     */
    java.util.List<java.lang.String>
        getValueList();
    /**
     * <code>repeated string value = 3;</code>
     * @return The count of value.
     */
    int getValueCount();
    /**
     * <code>repeated string value = 3;</code>
     * @param index The index of the element to return.
     * @return The value at the given index.
     */
    java.lang.String getValue(int index);
    /**
     * <code>repeated string value = 3;</code>
     * @param index The index of the element to return.
     * @return The value at the given index.
     */
    com.google.protobuf.ByteString
        getValueBytes(int index);
  }
  /**
   * Protobuf type {@code ProtoDefs.Param}
   */
  public  static final class Param extends
      com.google.protobuf.GeneratedMessageLite<
          Param, Param.Builder> implements
      // @@protoc_insertion_point(message_implements:ProtoDefs.Param)
      ParamOrBuilder {
    private Param() {
      object_ = "";
      type_ = "";
      value_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    public static final int OBJECT_FIELD_NUMBER = 1;
    private java.lang.String object_;
    /**
     * <code>string object = 1;</code>
     * @return The object.
     */
    @java.lang.Override
    public java.lang.String getObject() {
      return object_;
    }
    /**
     * <code>string object = 1;</code>
     * @return The bytes for object.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getObjectBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(object_);
    }
    /**
     * <code>string object = 1;</code>
     * @param value The object to set.
     */
    private void setObject(
        java.lang.String value) {
      value.getClass();
  
      object_ = value;
    }
    /**
     * <code>string object = 1;</code>
     */
    private void clearObject() {
      
      object_ = getDefaultInstance().getObject();
    }
    /**
     * <code>string object = 1;</code>
     * @param value The bytes for object to set.
     */
    private void setObjectBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      object_ = value.toStringUtf8();
      
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private java.lang.String type_;
    /**
     * <code>string type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      return type_;
    }
    /**
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(type_);
    }
    /**
     * <code>string type = 2;</code>
     * @param value The type to set.
     */
    private void setType(
        java.lang.String value) {
      value.getClass();
  
      type_ = value;
    }
    /**
     * <code>string type = 2;</code>
     */
    private void clearType() {
      
      type_ = getDefaultInstance().getType();
    }
    /**
     * <code>string type = 2;</code>
     * @param value The bytes for type to set.
     */
    private void setTypeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      type_ = value.toStringUtf8();
      
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> value_;
    /**
     * <code>repeated string value = 3;</code>
     * @return A list containing the value.
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getValueList() {
      return value_;
    }
    /**
     * <code>repeated string value = 3;</code>
     * @return The count of value.
     */
    @java.lang.Override
    public int getValueCount() {
      return value_.size();
    }
    /**
     * <code>repeated string value = 3;</code>
     * @param index The index of the element to return.
     * @return The value at the given index.
     */
    @java.lang.Override
    public java.lang.String getValue(int index) {
      return value_.get(index);
    }
    /**
     * <code>repeated string value = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the value at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          value_.get(index));
    }
    private void ensureValueIsMutable() {
      com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
          value_;  if (!tmp.isModifiable()) {
        value_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <code>repeated string value = 3;</code>
     * @param index The index to set the value at.
     * @param value The value to set.
     */
    private void setValue(
        int index, java.lang.String value) {
      value.getClass();
  ensureValueIsMutable();
      value_.set(index, value);
    }
    /**
     * <code>repeated string value = 3;</code>
     * @param value The value to add.
     */
    private void addValue(
        java.lang.String value) {
      value.getClass();
  ensureValueIsMutable();
      value_.add(value);
    }
    /**
     * <code>repeated string value = 3;</code>
     * @param values The value to add.
     */
    private void addAllValue(
        java.lang.Iterable<java.lang.String> values) {
      ensureValueIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, value_);
    }
    /**
     * <code>repeated string value = 3;</code>
     */
    private void clearValue() {
      value_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string value = 3;</code>
     * @param value The bytes of the value to add.
     */
    private void addValueBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      ensureValueIsMutable();
      value_.add(value.toStringUtf8());
    }

    public static ProtoDefs.LogStructure.Param parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProtoDefs.LogStructure.Param parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProtoDefs.LogStructure.Param parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProtoDefs.LogStructure.Param parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProtoDefs.LogStructure.Param parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProtoDefs.LogStructure.Param parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProtoDefs.LogStructure.Param parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProtoDefs.LogStructure.Param parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProtoDefs.LogStructure.Param parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ProtoDefs.LogStructure.Param parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProtoDefs.LogStructure.Param parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProtoDefs.LogStructure.Param parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ProtoDefs.LogStructure.Param prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code ProtoDefs.Param}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ProtoDefs.LogStructure.Param, Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoDefs.Param)
        ProtoDefs.LogStructure.ParamOrBuilder {
      // Construct using ProtoDefs.LogStructure.Param.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string object = 1;</code>
       * @return The object.
       */
      @java.lang.Override
      public java.lang.String getObject() {
        return instance.getObject();
      }
      /**
       * <code>string object = 1;</code>
       * @return The bytes for object.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getObjectBytes() {
        return instance.getObjectBytes();
      }
      /**
       * <code>string object = 1;</code>
       * @param value The object to set.
       * @return This builder for chaining.
       */
      public Builder setObject(
          java.lang.String value) {
        copyOnWrite();
        instance.setObject(value);
        return this;
      }
      /**
       * <code>string object = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearObject() {
        copyOnWrite();
        instance.clearObject();
        return this;
      }
      /**
       * <code>string object = 1;</code>
       * @param value The bytes for object to set.
       * @return This builder for chaining.
       */
      public Builder setObjectBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setObjectBytes(value);
        return this;
      }

      /**
       * <code>string type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public java.lang.String getType() {
        return instance.getType();
      }
      /**
       * <code>string type = 2;</code>
       * @return The bytes for type.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTypeBytes() {
        return instance.getTypeBytes();
      }
      /**
       * <code>string type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>string type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTypeBytes(value);
        return this;
      }

      /**
       * <code>repeated string value = 3;</code>
       * @return A list containing the value.
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getValueList() {
        return java.util.Collections.unmodifiableList(
            instance.getValueList());
      }
      /**
       * <code>repeated string value = 3;</code>
       * @return The count of value.
       */
      @java.lang.Override
      public int getValueCount() {
        return instance.getValueCount();
      }
      /**
       * <code>repeated string value = 3;</code>
       * @param index The index of the element to return.
       * @return The value at the given index.
       */
      @java.lang.Override
      public java.lang.String getValue(int index) {
        return instance.getValue(index);
      }
      /**
       * <code>repeated string value = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the value at the given index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes(int index) {
        return instance.getValueBytes(index);
      }
      /**
       * <code>repeated string value = 3;</code>
       * @param index The index to set the value at.
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setValue(index, value);
        return this;
      }
      /**
       * <code>repeated string value = 3;</code>
       * @param value The value to add.
       * @return This builder for chaining.
       */
      public Builder addValue(
          java.lang.String value) {
        copyOnWrite();
        instance.addValue(value);
        return this;
      }
      /**
       * <code>repeated string value = 3;</code>
       * @param values The value to add.
       * @return This builder for chaining.
       */
      public Builder addAllValue(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllValue(values);
        return this;
      }
      /**
       * <code>repeated string value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }
      /**
       * <code>repeated string value = 3;</code>
       * @param value The bytes of the value to add.
       * @return This builder for chaining.
       */
      public Builder addValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoDefs.Param)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ProtoDefs.LogStructure.Param();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "object_",
              "type_",
              "value_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u021a";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ProtoDefs.LogStructure.Param> parser = PARSER;
          if (parser == null) {
            synchronized (ProtoDefs.LogStructure.Param.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ProtoDefs.LogStructure.Param>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ProtoDefs.Param)
    private static final ProtoDefs.LogStructure.Param DEFAULT_INSTANCE;
    static {
      Param defaultInstance = new Param();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Param.class, defaultInstance);
    }

    public static ProtoDefs.LogStructure.Param getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Param> PARSER;

    public static com.google.protobuf.Parser<Param> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
